
repos:
- repo: local
  hooks:
    - id: phpstan
      name: Check PHP coding standards
      entry: podman exec -it uzerp-app-dev vendor/bin/phpstan analyse --autoload-file utils/dev/loader.php --memory-limit 512M
      language: system
      types: [php]
