rmdir modules/public_pages/erp/ledger/vat/reports/
rmdir modules/public_pages/erp/order/sales_order/reports/
rmdir modules/public_pages/erp/invoicing/sales_invoicing/reports/
rmdir modules/public_pages/quality/reports/
rmdir modules/public_pages/erp/order/purchase_order/reports/
rmdir modules/public_pages/erp/order/reports/
rmdir modules/public_pages/erp/ledger/reports/
rmdir modules/public_pages/erp/invoicing/reports/
rmdir modules/public_pages/erp/ledger/general_ledger/reports/
rmdir modules/public_pages/erp/despatch/reports/
rmdir modules/public_pages/erp/costing/reports/
rmdir modules/common/reports/
