#!/bin/bash
#
#	(c) 2000-2012 uzERP LLP (support#uzerp.com). All rights reserved.
#
#	Released under GPLv3 license; see LICENSE.
#
#
# compareReleaseVersions
#
# Compares the code in a release file with the current target code 
#
# Requires 3 parameters:-
# - Target code base directory
# - Release File name (without extension - assumes .tar.gz
# - Release directory containing release file
#-------------------------------------------------------------------------------
rootdir=
if [ "$#" -eq 0 -o "$1" = "-?" -o "${1:0:1}" = "H" -o "${1:0:1}" = "h" -o "${1:0:2}" = "-H" -o "${1:0:2}" = "-h" -o "${1:0:3}" = "--H" -o "${1:0:3}" = "--h" ]
then
  echo "Requires 3 parameters:-"
  echo "  - Target code base directory"
  echo "  - Release File name (without extension - assumes .tar.gz"
  echo "  - Release directory containing release file"
  exit -1
fi
if [ "$#" -lt 3 ]
then
  dir='.'
else
  dir=$3
fi
for i in `tar -ztf $dir/$2.tar.gz`
do
  if [ "${i: -1}" != "/" ]
  then
    file=${i#./}
    version=`tar -zxOf $dir/$2.tar.gz $i | grep '$Revision'`
    version=${version#*\$Revision: }
    current=`grep '$Revision' $1/$file`
    current=${current#*\$Revision: }
    echo "$file;Release ${version% \$*};Current ${current% \$*}"
  fi
done
