#!/bin/bash
#
#       (c) 2000-2012 uzERP LLP (support#uzerp.com). All rights reserved.
#
#       Released under GPLv3 license; see LICENSE.
#
# copy_backup_files
#
# $ Revision: $
#
# Makes a copy of the latest backup file saving as either the latest for that day or month depending on the period parameter
#
dir=`pwd`
if [ $# -ne 3 -o "$1" = "-?" -o "${1:0:1}" = "H" -o "${1:0:1}" = "h" -o "${1:0:2}" = "-H" -o "${1:0:2}" = "-h" -o "${1:0:3}" = "--H" -o "${1:0:3}" = "--h" ]
then
  echo "------------------------------------------------------"
  echo "copy_backup_files"
  echo ""
  echo "Makes a copy of the specified file giving the copy a name unique by day or month"
  echo ""
  echo "Requires 3 parameters:-"
  echo "  - Source File Name (with full path)"
  echo "  - target File Name (with full path to which will be added yyyy-mm or yyyy-mm-dd depending on period parameter)"
  echo "  - period (Daily or Monthly)"
  echo "------------------------------------------------------"
  exit -1
fi

if [ "${3:0:1}" = "M" -o "${3:0:1}" = "m" ]
then
  cut=7;
elif [ "${3:0:1}" = "D" -o "${3:0:1}" = "d" ]
then
  cut=10;
else
  echo "Invalid period parameter ${3:0:1}"
  exit -1
fi

newfile=`stat --printf=%y $1 | cut -d. -f1 | cut -c1-$cut`

cp $1 $2.$newfile

if [ $? -ne 0 ]
then
  echo "copy_backup_files - Error copying file"
  exit -1;
fi

#echo "copy_backup_files finished OK"
