#!/bin/bash
#
#	(c) 2000-2012 uzERP LLP (support#uzerp.com). All rights reserved.
#
#	Released under GPLv3 license; see LICENSE.
#
if [ "$#" -eq 3 ]
then
  if [ -d $1 ]
  then
    rundate=`date +%Y%m%d%H%M%S`
    tmp=/tmp/deleteFiles.txt
    echo $2 > $tmp
    logfile=$1/'deleteFiles'$rundate'.log'
    echo "Starting deleteFiles for `hostname` on" `date +%d/%m/%Y_%H:%M:%S` > $logfile
    echo "Deleting $1/$2 files older than" $3 "days" >> $logfile
    echo "" >> $logfile
    echo "-----------------------------------" >> $logfile
    find $1/ -maxdepth 1 -mtime +$3 -name "$2" >> $logfile
    find $1/ -maxdepth 1 -mtime +$3 -name "$2" -exec rm {} \;
    echo "-----------------------------------" >> $logfile
    echo "" >> $logfile
    echo "Finished deleteFiles for `hostname` at" `date +%d/%m/%Y_%H:%M:%S` >> $logfile
    echo "" >> $logfile
    echo "-----------------------------------" >> $logfile
#    cat $logfile
  fi
else
  echo "deleteFiles requires 3 parameters"
  echo "Parameter 1 must be a folder name containing the files to delete"
  echo "Parameter 2 must be a filename mask for the files to delete"
  echo "Parameter 3 must be the number of days beyond which files are to be deleted"
fi
