#!/bin/bash
#
#	(c) 2000-2012 uzERP LLP (support#uzerp.com). All rights reserved.
#
#	Released under GPLv3 license; see LICENSE.
#
#
# listCodeVersion
#
# Lists the current version of the specified file
#
# Parameters
# 1 - path to file
#
if [ "$#" -eq 0 -o "$1" = "-?" -o "${1:0:1}" = "H" -o "${1:0:1}" = "h" -o "${1:0:2}" = "-H" -o "${1:0:2}" = "-h" -o "${1:0:3}" = "--H" -o "${1:0:3}" = "--h" ]
then
  echo "---------------------------------------------------------"
  echo "listCodeVersion"
  echo ""
  echo "Requires 1 parameters:-"
  echo "  - file path"
  echo "---------------------------------------------------------"
  exit -1
fi
version=`grep '$Revision' $1`
version=${version#*\$Revision: }
echo $1";"${version% \$*}
