#!/bin/bash
#
#	(c) 2000-2012 uzERP LLP (support#uzerp.com). All rights reserved.
#
#	Released under GPLv3 license; see LICENSE.
#
# Simple script to do full vacuum of PostgreSQL databases

logfile=/var/log/postgresql/pg_vacuum.log

databases=`psql -q -l | sed -n 4,/\eof/p | grep -v rows\) | grep -v template | grep -v : | awk {'print $1'}`

echo "Postgres Full Vacuum " `date` > $logfile
echo "=========================================================" >> $logfile
echo >> $logfile
echo "Vacuuming:" >> $logfile
for i in $databases; do
        /usr/bin/vacuumdb -f $i >/dev/null 2>&1
        echo -e "\t $i" >> $logfile
done
echo "" >> $logfile
echo "Vacuuming Complete." `date` >> $logfile
cat $logfile
