name: build-release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Install node packages
        run: npm install
      - name: Set release version as tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Make build script executable
        run: sudo chmod a+x ./utils/uzerp-make-release
      - name: Build release
        run: ./utils/uzerp-make-release -r $RELEASE_VERSION -w /tmp
      - name: Generate md5 hash
        run: echo "RELEASE_HASH=$(md5sum /tmp/release-uzerp-${{ env.RELEASE_VERSION }}.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: "uzERP ${{ env.RELEASE_VERSION}}"
          body: |
            See https://github.com/uzerpllp/uzerp/blob/${{ env.RELEASE_VERSION}}/CHANGELOG.md for notable changes since the last uzERP release.
            
            md5: ${{ env.RELEASE_HASH}}
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: "/tmp/release-uzerp-${{ env.RELEASE_VERSION }}.tar.gz"
          asset_name: "release-uzerp-${{ env.RELEASE_VERSION }}.tar.gz"
          asset_content_type: application/tar+gzip
